apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels: {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels: {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "frontend.labels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: {{ printf "%s:%s" .Values.frontend.image.name .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
              name: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          env:
            - name: SIGNALLING_SERVER_URL
              value: {{ .Values.signalling.uri | quote }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" .}}
  labels: {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector: {{- include "frontend.selectorLabels" . | nindent 4 }}
