apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels: {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels: {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "frontend.labels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: {{ printf "%s:%s" .Values.frontend.image.name .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
              name: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          env:
            - name: NEXT_PUBLIC_SIGNALLING_SERVER_URL
              value: {{ .Values.signalling.uri | quote }}
            - name: NEXT_PUBLIC_OIDC_CLIENT_ID
              value: {{ .Values.frontend.keycloak.clientId | quote }}
            - name: NEXT_PUBLIC_OIDC_AUTHORITY_URL
              value: {{ .Values.frontend.keycloak.authorityUrl | quote }}
            - name: NEXT_PUBLIC_FRONTEND_PORT
              value: {{ .Values.gateway.port | quote }}
            - name: NEXT_PUBLIC_FRONTEND_BASE_URL
              value: {{ printf "https://%s" .Values.frontend.host | quote }}
            - name: NEXT_PUBLIC_JWT_AUDIENCE
              value: {{ .Values.frontend.keycloak.audience | quote }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" .}}
  labels: {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector: {{- include "frontend.selectorLabels" . | nindent 4 }}

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "gateway.route" . }}-frontend
spec:
  hostnames:
    - {{ .Values.frontend.host }}
  parentRefs:
    - name: {{ include "gateway.fullname" . }}
  rules:
    - backendRefs:
        - name: {{ include "frontend.fullname" . }}
          port: {{ .Values.frontend.port }}