apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "signalling.fullname" . }}
  labels: {{- include "signalling.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.signalling.replicas }}
  selector:
    matchLabels: {{- include "signalling.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "signalling.labels" . | nindent 8 }}
    spec:
      containers:
        - name: signalling
          image: {{ printf "%s:%s" .Values.signalling.image.name .Values.signalling.image.tag }}
          imagePullPolicy: {{ .Values.signalling.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.signalling.ws.port }}
              name: ws
          resources:
            {{- toYaml .Values.signalling.resources | nindent 12 }}
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.name }}-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.name }}-default-user
                  key: password
            - name: RABBITMQ_URL
              value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@{{ .Values.rabbitmq.name }}:5672
            - name: PORT
              value: "{{ .Values.signalling.ws.port }}"
            - name: DEFAULT_DB_TYPE
              value: postgres
            - name: DEFAULT_DB_HOST
              value: {{ include "cluster.app.fullname" .}}-rw
            - name: DEFAULT_DB_PORT
              value: "{{ .Values.databases.app.port }}"
            - name: DEFAULT_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.databases.app.secret }}
                  key: 'username'
            - name: DEFAULT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.databases.app.secret }}
                  key: 'password'
            - name: DEFAULT_DB_NAME
              value: {{ .Values.databases.app.name }}
            - name: DEFAULT_DB_LOGGING
              value: "false"
            - name: RUN_MIGRATIONS
              value: "true"

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "signalling.fullname" .}}
  labels: {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.signalling.ws.port }}
      targetPort: {{ .Values.signalling.ws.port }}
      protocol: TCP
      name: ws
  selector: {{- include "signalling.selectorLabels" . | nindent 4 }}

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "gateway.route" . }}-signalling
spec:
  hostnames:
    - {{ .Values.signalling.host }}
  parentRefs:
    - name: {{ include "gateway.fullname" . }}
  rules:
    - backendRefs:
        - name: {{ include "signalling.fullname" . }}
          port: {{ .Values.signalling.ws.port }}


